name: Teardown ROCm host

description: Teardown ROCm host for CI

runs:
  using: composite
  steps:
    - name: Kill containers, clean up images
      if: always()
      shell: bash
      run: |
        # ignore expansion of "docker ps -q" since it could be empty
        # shellcheck disable=SC2046
        docker stop $(docker ps -q) || true
        # Prune all of the docker containers
        docker container prune -f
        # Prune all of the docker images older than 1 day
        docker system prune -af --filter "until=24h"
